### ISSUE TITLE
Create and change organization icon

### ISSUE THREAD

**Issue by lucasb** [lucasb/leafbird#17]
Create and change organization icon.

**Comment by bscherer** [comment]
+1

**Comment by gitarno** [comment]
:+1:

**Comment by gitarno** [comment]
![leafbird](https://cloud.githubusercontent.com/assets/5985142/12343985/ee4ca3a0-bb1f-11e5-847d-7af852f73199.png)

**Comment by lucasb** [comment]
Nice, I will change project icon asap. :smiley:

**Comment by lucasb** [comment]
Great work @gitarno. Done.
