### ISSUE TITLE
Performance of loops

### ISSUE THREAD

**Issue by gitarno** [lucasb/leafbird#2]
Opening an issue for us to verify the code the actual need of using ``for (key in args)`` because if we can replace regressive basic loops we would have a gain of considerable performace, about 99%. See the example that [Jsperf](http://jsperf.com/fastest-array-loops-in-javascript/417)

**Comment by lucasb** [comment]
It sounds good. I will look for it, but you can feel free to make a pull request with that fix.

**Comment by gitarno** [comment]
Comparing the two loop (basic, in) the basic format have not all requirements, since the intention is to get the key of the object. [benchmark JS](http://jsperf.com/okey-for-array)
